# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed1e7d0b784abc190cd55a6061523337922ae7a329bfcca0f2e233f65bb5459e27c2ee7ae6a3e4ddbbe60a69a113b1ebb941b57175280215347f8fdf5282753d

test:
  secret_key_base: f8fbac60e791231f5084889f11ee2cc9f651567aea97806b30583cf4d046d2f9cc411b7fa920bfbe0e9d5f3265cc87caaf190b5be3036d9aa96a938e6889c2c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
