---
development:
  cloud_name: stephencheung
  api_key: '169922834481936'
  api_secret: "-g6NlAjQlsXmimNrduxa-wkQWqQ"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: stephencheung
  api_key: '169922834481936'
  api_secret: "-g6NlAjQlsXmimNrduxa-wkQWqQ"
  enhance_image_tag: true
  static_image_support: true
  secure: true;
test:
  cloud_name: stephencheung
  api_key: '169922834481936'
  api_secret: "-g6NlAjQlsXmimNrduxa-wkQWqQ"
  enhance_image_tag: true
  static_image_support: false
